version : "3"
services :
  mongodb:
    container_name: mongo-dev
    image: mongo
    ports:
      - '27017:27017'
  node:
    container_name: node
    restart: always
    build: .
    ports: 
      - "80:3000"
    depends_on:
      - mongodb
  rabbimq:
    container_name: rabbitmq-dev
    image: rabbitmq:latest
    environment:
      RABBITMQ_ERLANG_COOKIE : 'secret cookie'
    ports:
      - 15671:15671
      - 5672:5672


